apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/part-of: keda-infra
  name: keda-audit-log
  namespace: openshift-keda
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi # Configure according to your needs