apiVersion: v1
kind: Secret
metadata:
  name: prometheus-sa-token
  namespace: openshift-keda
  annotations:
    kubernetes.io/service-account.name: prometheus-sa
  labels:
    app.kubernetes.io/part-of: keda-infra
type: kubernetes.io/service-account-token
