apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-sa-crb
  labels:
    app: httpd-sample
    app.kubernetes.io/part-of: app
subjects:
  - kind: ServiceAccount
    name: prometheus-sa
    namespace: keda-demo
roleRef:
  kind: ClusterRole
  name: cluster-monitoring-view
  apiGroup: rbac.authorization.k8s.io
