apiVersion: v1
kind: Secret
metadata:
  name: prometheus-sa-token
  namespace: keda-demo
  annotations:
    kubernetes.io/service-account.name: prometheus-sa
  labels:
    app: httpd-sample
    app.kubernetes.io/part-of: app
type: kubernetes.io/service-account-token
