apiVersion: v1
kind: Secret
metadata:
  name: grafana-sa-token
  namespace: keda-demo
  annotations:
    kubernetes.io/service-account.name: grafana-sa
  labels:
    app.kubernetes.io/part-of: grafana-infra
type: kubernetes.io/service-account-token
