apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: monitoring-folder
  namespace: keda-demo
  labels:
    app: grafana
    app.kubernetes.io/part-of: grafana-infra
spec:
  # If title is not defined, the value will be taken from metadata.name
  title: Monitoring
  instanceSelector:
    matchLabels:
      dashboards: grafana
